from . import property
from . import configuration
from . import project
from . import property_reservation
from . import ir_attachment
from . import res_partner
from . import account_payment
from . import installment_line
from . import payment_strategy_line
from . import account_payment_term
from . import sale_order
