from . import hr_leave_type_inherit
from . import hr_employee_inherit
from . import hr_termination_request
from . import hr_resignation_request
from . import employee_Config_rules
from . import hr_termination_rules
from . import hr_resignation_rule
from . import end_of_service_recognition
from . import eos_recongintion_indemnity
from . import res_config_setting
