# -*- coding: utf-8 -*-
# Copyright 2022 Verts Services India Pvt Ltd.
# http://www.verts.co.in

{
    "name": "verts_v15_freight_forward",
    "version": "18.0.1.0.0",
    "author": "VERTS Services India Pvt. Ltd.",
    "description": """This module adds the features of finance localization related to India""",
    "website": "http://www.verts.co.in",
    "depends": ['sale', 'stock', 'sale_management', 'purchase', 'verts_v15_basic_masters', 'verts_v15_print_template',
                'product', 'crm'
                ],
    "category": "Generic Modules",
    'license': "LGPL-3",
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        "data/sequence.xml",
        ##'wizard/export_invoice_details_view.xml', ##by kajal
        ##'wizard/meis_report_wiz_view.xml', ##by kajal
        # 'wizard/export_attachment_view.xml',
        'data/ecgc_rating_data.xml',
        'data/bill_of_lading_data.xml',
        'data/payment_term_data.xml',
        'data/port_data.xml',
        'data/transit_duration_data.xml',
        'data/point_of_stuffing_data.xml',
        'data/empty_trailer_cost_data.xml',
        'data/export_expense_data.xml',
        'data/qc_parameter_data.xml',
        'data/freight_uom.xml',
        'data/account_journal.xml',
        'views/exports_view.xml',
        'views/res_country_view.xml',
        'views/product_view.xml',
        # 'views/sale_view.xml',
        'views/view_cargo_order.xml',
        'views/res_partner_view.xml',
        # 'views/purchase_views.xml',
        # 'views/export_pro_categ_view.xml',
        # 'views/qc_parameter_view.xml',
        # 'views/spice_board_view.xml',
        # 'views/common_schedule_view.xml',
        # 'views/stock_view.xml',
        'views/air_import_view.xml',
        # 'views/awb_master_view.xml',
        # 'views/res_bank_view.xml',
        # 'views/account_payment_register_wiz.xml',
        # 'reports/report_paperformat.xml',
        # 'reports/cv_csr_report.xml',
        # 'views/cv_csr_report_view.xml',
        # 'views/air_export_view.xml',
        # 'views/account_view.xml',  ##by kajal
        'views/so_invoice_val.xml',
        # 'views/view_ocean_vessel.xml',
        # 'views/view_voyage.xml',
        # 'views/view_bill_lading_type.xml',
        'views/job_order_view.xml',
        'views/payment_view.xml',
        # 'views/hr_view.xml',
        'views/menu_view.xml',
        'reports/cargo_arrival_report.xml',
        'reports/proof_of_delivery.xml',
        'reports/sale_order_report.xml',
        'reports/agent_quote_report.xml',
        'reports/agent_order_report.xml',
        'reports/sale_quote_report.xml',
        # 'reports/awb_report.xml',
        'reports/ff_invoice_report.xml',
        # 'reports/freight_invoice_report.xml', ##by kajal
        # 'reports/allergen_declartion_report.xml',
        # 'reports/cargo_report.xml',
        # 'reports/container_corp_of_india.xml',
        'reports/performa_invoice_template_view.xml',
        'reports/export_invoice_template.xml',
        'reports/payment_and_receipt_report.xml',
        'reports/payment_recipet_report_journal.xml',
        'reports/payment_voucher_receipt.xml',
        'reports/payment_report.xml',
        # 'reports/payment_receipt_report.xml',
        'reports/journal_payment_and_receipt_report.xml',
        'reports/label.xml',
        #                     'reports/samay_agro_pdf2.xml',
        #                     'reports/analytic_report.xml',
        #                     'reports/certificiate_of_weight.xml',
        #                     'reports/gmo_declaration.xml',
        #                     'reports/export_credit_guarantee_center.xml',
        #                     'reports/index_report.xml',
        #                    'reports/epriornotice_template_view.xml',
        #                     'reports/certificate_of_analysis.xml',
        #                   'reports/kalustyan_template_view.xml',
        #                    'reports/sales_contract_report.xml',
        #                    'reports/generalized_template_view.xml',
        #                  'reports/estimated_template_view.xml',
        #                   'reports/marine_insurance_pdf17.xml',
        #                    'reports/sales_agro_pdf11.xml',
        #                     'reports/work_order_report_view.xml',
        #                     'reports/work_order_report_template_view.xml',
        #                     'reports/health_certificate_template_view.xml',
        #                     'reports/price_checkl_list_report.xml',
        #                     'reports/price_check_list_template_view.xml',
        #                    'reports/samay_agro_pdf18.xml',
        #                     'reports/sale_order_report.xml',
        # 'reports/faculty_report.xml',
        #                     'reports/sale_contract_view.xml',
        #                     'reports/sale_contract_template_view.xml',
        #                     'reports/packing_list_view.xml',
        #                     'reports/packing_list_template_view.xml',

    ],
    'test': [],
    'installable': True,
    'active': False,
    'certificate': '',
}
